In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('Most_Streamed_Spotify_Songs2024.csv', encoding='latin1')

In [ ]:
df

Track                        Album Name  \
0                 MILLION DOLLAR BABY      Million Dollar Baby - Single   
1                         Not Like Us                       Not Like Us   
2          i like the way you kiss me        I like the way you kiss me   
3                             Flowers                  Flowers - Single   
4                             Houdini                           Houdini   
...                               ...                               ...   
4595                For the Last Time                 For the Last Time   
4596                 Dil Meri Na Sune  Dil Meri Na Sune (From "Genius")   
4597            Grace (feat. 42 Dugg)                           My Turn   
4598              Nashe Si Chadh Gayi             November Top 10 Songs   
4599  Me Acostumbre (feat. Bad Bunny)   Me Acostumbre (feat. Bad Bunny)   

              Artist Release Date          ISRC All Time Rank  Track Score  \
0      Tommy Richman    4/26/2024  QM24S2402528             1        725.4   
1     Kendrick Lamar     5/4/2024  USUG12400910             2        545.9   
2            Artemas    3/19/2024  QZJ842400387             3        538.4   
3        Miley Cyrus    1/12/2023  USSM12209777             4        444.9   
4             Eminem    5/31/2024  USUG12403398             5        423.3   
...              ...          ...           ...           ...          ...   
4595     $uicideboy$     9/5/2017  QM8DG1703420         4,585         19.4   
4596      Atif Aslam    7/27/2018  INT101800122         4,575         19.4   
4597        Lil Baby    2/28/2020  USUG12000043         4,571         19.4   
4598    Arijit Singh    11/8/2016  INY091600067         4,591         19.4   
4599       Arc��    4/11/2017  USB271700107         4,593         19.4   

     Spotify Streams Spotify Playlist Count Spotify Playlist Reach  ...  \
0        390,470,936                 30,716            196,631,588  ...   
1        323,703,884                 28,113            174,597,137  ...   
2        601,309,283                 54,331            211,607,669  ...   
3      2,031,280,633                269,802            136,569,078  ...   
4        107,034,922                  7,223            151,469,874  ...   
...              ...                    ...                    ...  ...   
4595     305,049,963                 65,770              5,103,054  ...   
4596      52,282,360                  4,602              1,449,767  ...   
4597     189,972,685                 72,066              6,704,802  ...   
4598     145,467,020                 14,037              7,387,064  ...   
4599     255,740,653                 32,138             14,066,526  ...   

      SiriusXM Spins Deezer Playlist Count Deezer Playlist Reach  \
0                684                  62.0            17,598,718   
1                  3                  67.0            10,422,430   
2                536                 136.0            36,321,847   
3              2,182                 264.0            24,684,248   
4                  1                  82.0            17,660,624   
...              ...                   ...                   ...   
4595             NaN                   2.0                14,217   
4596             NaN                   1.0                   927   
4597             NaN                   1.0                    74   
4598             NaN                   NaN                   NaN   
4599             NaN                   4.0               127,479   

     Amazon Playlist Count Pandora Streams Pandora Track Stations  \
0                    114.0      18,004,655                 22,931   
1                    111.0       7,780,028                 28,444   
2                    172.0       5,022,621                  5,639   
3                    210.0     190,260,277                203,384   
4                    105.0       4,493,884                  7,006   
...                    ...             ...                    

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Track                       4600 non-null   object 
 1   Album Name                  4600 non-null   object 
 2   Artist                      4595 non-null   object 
 3   Release Date                4600 non-null   object 
 4   ISRC                        4600 non-null   object 
 5   All Time Rank               4600 non-null   object 
 6   Track Score                 4600 non-null   float64
 7   Spotify Streams             4487 non-null   object 
 8   Spotify Playlist Count      4530 non-null   object 
 9   Spotify Playlist Reach      4528 non-null   object 
 10  Spotify Popularity          3796 non-null   float64
 11  YouTube Views               4292 non-null   object 
 12  YouTube Likes               4285 non-null   object 
 13  TikTok Posts                3427 

In [ ]:
df.fillna(method = 'ffill', inplace= True)
df

Track                        Album Name  \
0                 MILLION DOLLAR BABY      Million Dollar Baby - Single   
1                         Not Like Us                       Not Like Us   
2          i like the way you kiss me        I like the way you kiss me   
3                             Flowers                  Flowers - Single   
4                             Houdini                           Houdini   
...                               ...                               ...   
4595                For the Last Time                 For the Last Time   
4596                 Dil Meri Na Sune  Dil Meri Na Sune (From "Genius")   
4597            Grace (feat. 42 Dugg)                           My Turn   
4598              Nashe Si Chadh Gayi             November Top 10 Songs   
4599  Me Acostumbre (feat. Bad Bunny)   Me Acostumbre (feat. Bad Bunny)   

              Artist Release Date          ISRC All Time Rank  Track Score  \
0      Tommy Richman    4/26/2024  QM24S2402528             1        725.4   
1     Kendrick Lamar     5/4/2024  USUG12400910             2        545.9   
2            Artemas    3/19/2024  QZJ842400387             3        538.4   
3        Miley Cyrus    1/12/2023  USSM12209777             4        444.9   
4             Eminem    5/31/2024  USUG12403398             5        423.3   
...              ...          ...           ...           ...          ...   
4595     $uicideboy$     9/5/2017  QM8DG1703420         4,585         19.4   
4596      Atif Aslam    7/27/2018  INT101800122         4,575         19.4   
4597        Lil Baby    2/28/2020  USUG12000043         4,571         19.4   
4598    Arijit Singh    11/8/2016  INY091600067         4,591         19.4   
4599       Arc��    4/11/2017  USB271700107         4,593         19.4   

     Spotify Streams Spotify Playlist Count Spotify Playlist Reach  ...  \
0        390,470,936                 30,716            196,631,588  ...   
1        323,703,884                 28,113            174,597,137  ...   
2        601,309,283                 54,331            211,607,669  ...   
3      2,031,280,633                269,802            136,569,078  ...   
4        107,034,922                  7,223            151,469,874  ...   
...              ...                    ...                    ...  ...   
4595     305,049,963                 65,770              5,103,054  ...   
4596      52,282,360                  4,602              1,449,767  ...   
4597     189,972,685                 72,066              6,704,802  ...   
4598     145,467,020                 14,037              7,387,064  ...   
4599     255,740,653                 32,138             14,066,526  ...   

      SiriusXM Spins Deezer Playlist Count Deezer Playlist Reach  \
0                684                  62.0            17,598,718   
1                  3                  67.0            10,422,430   
2                536                 136.0            36,321,847   
3              2,182                 264.0            24,684,248   
4                  1                  82.0            17,660,624   
...              ...                   ...                   ...   
4595              13                   2.0                14,217   
4596              13                   1.0                   927   
4597              13                   1.0                    74   
4598              13                   1.0                    74   
4599              13                   4.0               127,479   

     Amazon Playlist Count Pandora Streams Pandora Track Stations  \
0                    114.0      18,004,655                 22,931   
1                    111.0       7,780,028                 28,444   
2                    172.0       5,022,621                  5,639   
3                    210.0     190,260,277                203,384   
4                    105.0       4,493,884                  7,006   
...                    ...             ...                    

In [ ]:
df.isnull().sum()

Track                            0
Album Name                       0
Artist                           0
Release Date                     0
ISRC                             0
All Time Rank                    0
Track Score                      0
Spotify Streams                  0
Spotify Playlist Count           0
Spotify Playlist Reach           0
Spotify Popularity               0
YouTube Views                    0
YouTube Likes                    0
TikTok Posts                     0
TikTok Likes                     0
TikTok Views                     0
YouTube Playlist Reach           0
Apple Music Playlist Count       0
AirPlay Spins                    0
SiriusXM Spins                   0
Deezer Playlist Count            0
Deezer Playlist Reach            0
Amazon Playlist Count            0
Pandora Streams                  0
Pandora Track Stations           0
Soundcloud Streams               0
Shazam Counts                    0
TIDAL Popularity              4600
Explicit Track      

In [ ]:
df.drop(['TIDAL Popularity'], axis = 1, inplace = True)
df.isnull().sum()

Track                         0
Album Name                    0
Artist                        0
Release Date                  0
ISRC                          0
All Time Rank                 0
Track Score                   0
Spotify Streams               0
Spotify Playlist Count        0
Spotify Playlist Reach        0
Spotify Popularity            0
YouTube Views                 0
YouTube Likes                 0
TikTok Posts                  0
TikTok Likes                  0
TikTok Views                  0
YouTube Playlist Reach        0
Apple Music Playlist Count    0
AirPlay Spins                 0
SiriusXM Spins                0
Deezer Playlist Count         0
Deezer Playlist Reach         0
Amazon Playlist Count         0
Pandora Streams               0
Pandora Track Stations        0
Soundcloud Streams            0
Shazam Counts                 0
Explicit Track                0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 28 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Track                       4600 non-null   object 
 1   Album Name                  4600 non-null   object 
 2   Artist                      4600 non-null   object 
 3   Release Date                4600 non-null   object 
 4   ISRC                        4600 non-null   object 
 5   All Time Rank               4600 non-null   object 
 6   Track Score                 4600 non-null   float64
 7   Spotify Streams             4600 non-null   object 
 8   Spotify Playlist Count      4600 non-null   object 
 9   Spotify Playlist Reach      4600 non-null   object 
 10  Spotify Popularity          4600 non-null   float64
 11  YouTube Views               4600 non-null   object 
 12  YouTube Likes               4600 non-null   object 
 13  TikTok Posts                4600 

In [ ]:
Z = ['Track', 'Album Name', 'Artist', 'Release Date','ISRC', 'All Time Rank', 'Spotify Streams','Spotify Playlist Count','Spotify Playlist Reach','YouTube Views','YouTube Likes', 'TikTok Likes','TikTok Views', 'TikTok Posts','YouTube Playlist Reach', 'AirPlay Spins','SiriusXM Spins','Deezer Playlist Reach','Pandora Streams','Pandora Track Stations', 'Soundcloud Streams','Shazam Counts']
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in Z:
    df[i] = le.fit_transform(df[i])


In [ ]:
df

Track  Album Name  Artist  Release Date  ISRC  All Time Rank  \
0      2191        2174    1754           870  1306              0   
1      2559        2389     953          1046  3750           1111   
2      4229        1580     136           705  1846           2221   
3      1278        1217    1234            35  3377           3331   
4      1603        1516     576          1039  3795           4022   
...     ...         ...     ...           ...   ...            ...   
4595   1288        1230       2          1542  1482           3901   
4596    969         919     142          1273   957           3900   
4597   1444        2260    1055           623  3526           3899   
4598   2461        2398     131           399   991           3903   
4599   2278        2116     125           801  2691           3904   

      Track Score  Spotify Streams  Spotify Playlist Count  \
0           725.4             2542                    2208   
1           545.9             2231                    1983   
2           538.4             3412                    3057   
3           444.9             1376                    1928   
4           423.3              582                    3516   
...           ...              ...                     ...   
4595         19.4             2139                    3401   
4596         19.4             3111                    2618   
4597         19.4             1307                    3610   
4598         19.4              956                     724   
4599         19.4             1836                    2271   

      Spotify Playlist Reach  ...  AirPlay Spins  SiriusXM Spins  \
0                       1376  ...           2169             571   
1                       1192  ...           2166             308   
2                       1704  ...           2910             502   
3                        745  ...            145             192   
4                        961  ...            462               0   
...                      ...  ...            ...             ...   
4595                    3144  ...           2593             115   
4596                      76  ...           2194             115   
4597                    3566  ...           1280             115   
4598                    3833  ...             66             115   
4599                     764  ...           1089             115   

      Deezer Playlist Count  Deezer Playlist Reach  Amazon Playlist Count  \
0                      62.0                    931                  114.0   
1                      67.0                    442                  111.0   
2                     136.0                   2067                  172.0   
3                     264.0                   1497                  210.0   
4                      82.0                    933                  105.0   
...                     ...                    ...                    ...   
4595                    2.0                    749                    8.0   
4596                    1.0                   3480                    8.0   
4597                    1.0                   3130                    6.0   
4598                    1.0                   3130                    7.0   
4599                    4.0                    656                    4.0   

      Pandora Streams  Pandora Track Stations  Soundcloud Streams  \
0                 862                    1136                 828   
1                2999                    1321                1024   
2                2447                    2113                1086   
3                 982                    1066                1086   
4                2160                    2495                 496   
...               ...                     ...                 ...   
4595             1171                     526                 939   
4596             1171                     526                 939   
4597             3252                    1332            

In [ ]:
df.corr()

Track  Album Name    Artist  Release Date  \
Track                       1.000000    0.654693 -0.002935      0.010466   
Album Name                  0.654693    1.000000  0.003145      0.004980   
Artist                     -0.002935    0.003145  1.000000      0.016887   
Release Date                0.010466    0.004980  0.016887      1.000000   
ISRC                        0.030765    0.034365  0.072608      0.015403   
All Time Rank               0.015619   -0.008368  0.006935     -0.024903   
Track Score                 0.001260    0.007803 -0.003606      0.031244   
Spotify Streams            -0.021888    0.003693 -0.022770     -0.012715   
Spotify Playlist Count     -0.032318   -0.009352 -0.022571      0.019449   
Spotify Playlist Reach     -0.023670   -0.011278  0.009362     -0.044640   
Spotify Popularity          0.040435    0.039367 -0.014604     -0.037590   
YouTube Views               0.021260    0.012166  0.009265     -0.034080   
YouTube Likes              -0.005301   -0.001296 -0.000447     -0.012277   
TikTok Posts               -0.018835   -0.022224  0.007762      0.027568   
TikTok Likes                0.030306    0.017554 -0.027445      0.006882   
TikTok Views                0.011635    0.016263 -0.016726      0.023027   
YouTube Playlist Reach      0.003732    0.009759  0.005599      0.018157   
Apple Music Playlist Count  0.024349    0.000472 -0.015590     -0.088376   
AirPlay Spins               0.003587    0.000473  0.000999     -0.002972   
SiriusXM Spins             -0.018413    0.012031  0.023607      0.005145   
Deezer Playlist Count       0.003394   -0.026534 -0.020769     -0.090994   
Deezer Playlist Reach       0.029490    0.003124  0.005663     -0.004979   
Amazon Playlist Count       0.017432    0.006311 -0.003769     -0.030236   
Pandora Streams             0.014638    0.013891 -0.000411     -0.008065   
Pandora Track Stations     -0.000727   -0.007476 -0.009148     -0.012310   
Soundcloud Streams          0.006394   -0.022424  0.015019      0.018579   
Shazam Counts              -0.017489   -0.010833  0.016075     -0.000899   
Explicit Track              0.006830    0.031438  0.008247      0.058769   

                                ISRC  All Time Rank  Track Score  \
Track                       0.030765       0.015619     0.001260   
Album Name                  0.034365      -0.008368     0.007803   
Artist                      0.072608       0.006935    -0.003606   
Release Date                0.015403      -0.024903     0.031244   
ISRC                        1.000000       0.020519     0.067891   
All Time Rank               0.020519       1.000000     0.068856   
Track Score                 0.067891       0.068856     1.000000   
Spotify Streams             0.030205      -0.022230    -0.045950   
Spotify Playlist Count      0.037096      -0.026343    -0.057062   
Spotify Playlist Reach     -0.008297       0.019585     0.041971   
Spotify Popularity          0.123239      -0.005013     0.200948   
YouTube Views               0.004506      -0.024079    -0.034211   
YouTube Likes              -0.008334      -0.028840    -0.036508   
TikTok Posts                0.008779       0.001714    -0.013131   
TikTok Likes                0.009334       0.004951     0.018021   
TikTok Views               -0.002548      -0.014231    -0.011150   
YouTube Playlist Reach     -0.005306      -0.006001    -0.021278   
Apple Music Playlist Count  0.109050       0.032612     0.414375   
AirPlay Spins              -0.013748      -0.005554     0.038238   
SiriusXM Spins             -0.011502      -0.049813     0.010712   
Deezer Playlist Count       0.005739       0.036795     0.349053   
Deezer Playlist Reach      -0.003699      -0.003889    -0.056927   
Amazon Playlist Count       0.096223       0.038609     0.560201   
Pandora Streams             0.008608      -0.003305    -0.001883   
Pandora Track Stations     -0.005432       0.006089     0.031248   
Soundcloud Streams          0.004271       0.019137    -0.

# **REGRESSION**

# *predicting track score*


In [ ]:
df.drop(['Artist', 'Spotify Streams','Spotify Playlist Count', 'Deezer Playlist Reach', 'Pandora Streams',	'Soundcloud Streams'	,'Shazam Counts', 'YouTube Views','YouTube Likes', 'TikTok Views', 'TikTok Posts', 'YouTube Playlist Reach'], axis = 1, inplace = True)

In [ ]:
X = df.loc[:,['Amazon Playlist Count']].values
Y = df.loc[:,['Track Score']].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [ ]:
from sklearn.metrics import r2_score
Y_pred = regressor.predict(X_test)
r2_score(Y_test, Y_pred)

0.3173202549538344

In [ ]:
X = df.loc[:, ['Track',	'Album Name',	'Release Date',	'ISRC',	'All Time Rank'	, 'Track Score',	'Spotify Playlist Reach',	'Spotify Popularity',	'TikTok Likes',	'Apple Music Playlist Count',	'AirPlay Spins',	'SiriusXM Spins',	'Deezer Playlist Count',	'Amazon Playlist Count',	'Pandora Track Stations',	'Explicit Track']].values
Y = df.loc[:,['Track Score']].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state = 0)

***MULTIPLE LINEAR REGRESSION***

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [ ]:
from sklearn.metrics import r2_score
Y_pred = regressor.predict(X_test)
r2_score(Y_test, Y_pred)

1.0

***SUPPORT VECTOR REGRESSOR***

In [ ]:
# FEATURE SCALEING
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_Y = StandardScaler()
X= sc_X.fit_transform(X)
Y = sc_Y.fit_transform(Y)

In [ ]:
from sklearn.svm import SVR
regressor = SVR(kernel ='linear')
regressor.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(kernel='linear')

In [ ]:
from sklearn.metrics import r2_score
Y_pred = regressor.predict(X_test)
r2_score(Y_test, Y_pred)

0.9999987289668731

***DECISION TREE***

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state =0)
regressor.fit(X_train,Y_train)

DecisionTreeRegressor(random_state=0)

In [ ]:
from sklearn.metrics import r2_score
Y_pred = regressor.predict(X_test)
r2_score(Y_test, Y_pred)

0.9710480102962308

***RANDOM FOREST***

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X,Y)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(n_estimators=10, random_state=0)

In [ ]:
from sklearn.metrics import r2_score
Y_pred = regressor.predict(X_test)
r2_score(Y, regressor.predict(X))

0.9949346904678172

In [ ]:
data = np.array([0.31732, 1.0 , 0.9999, 0.97104, 0.99493])

# providing an index
ser = pd.Series(data, index=['Simple Linear Regression', 'Multiple Linear Regression', 'SVM', 'DECSION_TREE', 'RANDOM_FOREST'])

print(ser)

Simple Linear Regression      0.31732
Multiple Linear Regression    1.00000
SVM                           0.99990
DECSION_TREE                  0.97104
RANDOM_FOREST                 0.99493
dtype: float64


# **CLASSIFICATION**

In [ ]:
df = pd.read_csv('Most_Streamed_Spotify_Songs2024.csv', encoding='latin1')

In [ ]:
df

Track                        Album Name  \
0                 MILLION DOLLAR BABY      Million Dollar Baby - Single   
1                         Not Like Us                       Not Like Us   
2          i like the way you kiss me        I like the way you kiss me   
3                             Flowers                  Flowers - Single   
4                             Houdini                           Houdini   
...                               ...                               ...   
4595                For the Last Time                 For the Last Time   
4596                 Dil Meri Na Sune  Dil Meri Na Sune (From "Genius")   
4597            Grace (feat. 42 Dugg)                           My Turn   
4598              Nashe Si Chadh Gayi             November Top 10 Songs   
4599  Me Acostumbre (feat. Bad Bunny)   Me Acostumbre (feat. Bad Bunny)   

              Artist Release Date          ISRC All Time Rank  Track Score  \
0      Tommy Richman    4/26/2024  QM24S2402528             1        725.4   
1     Kendrick Lamar     5/4/2024  USUG12400910             2        545.9   
2            Artemas    3/19/2024  QZJ842400387             3        538.4   
3        Miley Cyrus    1/12/2023  USSM12209777             4        444.9   
4             Eminem    5/31/2024  USUG12403398             5        423.3   
...              ...          ...           ...           ...          ...   
4595     $uicideboy$     9/5/2017  QM8DG1703420         4,585         19.4   
4596      Atif Aslam    7/27/2018  INT101800122         4,575         19.4   
4597        Lil Baby    2/28/2020  USUG12000043         4,571         19.4   
4598    Arijit Singh    11/8/2016  INY091600067         4,591         19.4   
4599       Arc��    4/11/2017  USB271700107         4,593         19.4   

     Spotify Streams Spotify Playlist Count Spotify Playlist Reach  ...  \
0        390,470,936                 30,716            196,631,588  ...   
1        323,703,884                 28,113            174,597,137  ...   
2        601,309,283                 54,331            211,607,669  ...   
3      2,031,280,633                269,802            136,569,078  ...   
4        107,034,922                  7,223            151,469,874  ...   
...              ...                    ...                    ...  ...   
4595     305,049,963                 65,770              5,103,054  ...   
4596      52,282,360                  4,602              1,449,767  ...   
4597     189,972,685                 72,066              6,704,802  ...   
4598     145,467,020                 14,037              7,387,064  ...   
4599     255,740,653                 32,138             14,066,526  ...   

      SiriusXM Spins Deezer Playlist Count Deezer Playlist Reach  \
0                684                  62.0            17,598,718   
1                  3                  67.0            10,422,430   
2                536                 136.0            36,321,847   
3              2,182                 264.0            24,684,248   
4                  1                  82.0            17,660,624   
...              ...                   ...                   ...   
4595             NaN                   2.0                14,217   
4596             NaN                   1.0                   927   
4597             NaN                   1.0                    74   
4598             NaN                   NaN                   NaN   
4599             NaN                   4.0               127,479   

     Amazon Playlist Count Pandora Streams Pandora Track Stations  \
0                    114.0      18,004,655                 22,931   
1                    111.0       7,780,028                 28,444   
2                    172.0       5,022,621                  5,639   
3                    210.0     190,260,277                203,384   
4                    105.0       4,493,884                  7,006   
...                    ...             ...                    

In [ ]:
df.fillna(method = 'ffill', inplace= True)
df

Track                        Album Name  \
0                 MILLION DOLLAR BABY      Million Dollar Baby - Single   
1                         Not Like Us                       Not Like Us   
2          i like the way you kiss me        I like the way you kiss me   
3                             Flowers                  Flowers - Single   
4                             Houdini                           Houdini   
...                               ...                               ...   
4595                For the Last Time                 For the Last Time   
4596                 Dil Meri Na Sune  Dil Meri Na Sune (From "Genius")   
4597            Grace (feat. 42 Dugg)                           My Turn   
4598              Nashe Si Chadh Gayi             November Top 10 Songs   
4599  Me Acostumbre (feat. Bad Bunny)   Me Acostumbre (feat. Bad Bunny)   

              Artist Release Date          ISRC All Time Rank  Track Score  \
0      Tommy Richman    4/26/2024  QM24S2402528             1        725.4   
1     Kendrick Lamar     5/4/2024  USUG12400910             2        545.9   
2            Artemas    3/19/2024  QZJ842400387             3        538.4   
3        Miley Cyrus    1/12/2023  USSM12209777             4        444.9   
4             Eminem    5/31/2024  USUG12403398             5        423.3   
...              ...          ...           ...           ...          ...   
4595     $uicideboy$     9/5/2017  QM8DG1703420         4,585         19.4   
4596      Atif Aslam    7/27/2018  INT101800122         4,575         19.4   
4597        Lil Baby    2/28/2020  USUG12000043         4,571         19.4   
4598    Arijit Singh    11/8/2016  INY091600067         4,591         19.4   
4599       Arc��    4/11/2017  USB271700107         4,593         19.4   

     Spotify Streams Spotify Playlist Count Spotify Playlist Reach  ...  \
0        390,470,936                 30,716            196,631,588  ...   
1        323,703,884                 28,113            174,597,137  ...   
2        601,309,283                 54,331            211,607,669  ...   
3      2,031,280,633                269,802            136,569,078  ...   
4        107,034,922                  7,223            151,469,874  ...   
...              ...                    ...                    ...  ...   
4595     305,049,963                 65,770              5,103,054  ...   
4596      52,282,360                  4,602              1,449,767  ...   
4597     189,972,685                 72,066              6,704,802  ...   
4598     145,467,020                 14,037              7,387,064  ...   
4599     255,740,653                 32,138             14,066,526  ...   

      SiriusXM Spins Deezer Playlist Count Deezer Playlist Reach  \
0                684                  62.0            17,598,718   
1                  3                  67.0            10,422,430   
2                536                 136.0            36,321,847   
3              2,182                 264.0            24,684,248   
4                  1                  82.0            17,660,624   
...              ...                   ...                   ...   
4595              13                   2.0                14,217   
4596              13                   1.0                   927   
4597              13                   1.0                    74   
4598              13                   1.0                    74   
4599              13                   4.0               127,479   

     Amazon Playlist Count Pandora Streams Pandora Track Stations  \
0                    114.0      18,004,655                 22,931   
1                    111.0       7,780,028                 28,444   
2                    172.0       5,022,621                  5,639   
3                    210.0     190,260,277                203,384   
4                    105.0       4,493,884                  7,006   
...                    ...             ...                    

In [ ]:
df.drop(['TIDAL Popularity'], axis = 1, inplace = True)
df.isnull().sum()

Track                         0
Album Name                    0
Artist                        0
Release Date                  0
ISRC                          0
All Time Rank                 0
Track Score                   0
Spotify Streams               0
Spotify Playlist Count        0
Spotify Playlist Reach        0
Spotify Popularity            0
YouTube Views                 0
YouTube Likes                 0
TikTok Posts                  0
TikTok Likes                  0
TikTok Views                  0
YouTube Playlist Reach        0
Apple Music Playlist Count    0
AirPlay Spins                 0
SiriusXM Spins                0
Deezer Playlist Count         0
Deezer Playlist Reach         0
Amazon Playlist Count         0
Pandora Streams               0
Pandora Track Stations        0
Soundcloud Streams            0
Shazam Counts                 0
Explicit Track                0
dtype: int64

In [ ]:
Z = ['Track', 'Album Name', 'Artist', 'Release Date','ISRC', 'All Time Rank', 'Spotify Streams','Spotify Playlist Count','Spotify Playlist Reach','YouTube Views','YouTube Likes', 'TikTok Likes','TikTok Views', 'TikTok Posts','YouTube Playlist Reach', 'AirPlay Spins','SiriusXM Spins','Deezer Playlist Reach','Pandora Streams','Pandora Track Stations', 'Soundcloud Streams','Shazam Counts']
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in Z:
    df[i] = le.fit_transform(df[i])


In [ ]:
df.corr()

Track  Album Name    Artist  Release Date  \
Track                       1.000000    0.654693 -0.002935      0.010466   
Album Name                  0.654693    1.000000  0.003145      0.004980   
Artist                     -0.002935    0.003145  1.000000      0.016887   
Release Date                0.010466    0.004980  0.016887      1.000000   
ISRC                        0.030765    0.034365  0.072608      0.015403   
All Time Rank               0.015619   -0.008368  0.006935     -0.024903   
Track Score                 0.001260    0.007803 -0.003606      0.031244   
Spotify Streams            -0.021888    0.003693 -0.022770     -0.012715   
Spotify Playlist Count     -0.032318   -0.009352 -0.022571      0.019449   
Spotify Playlist Reach     -0.023670   -0.011278  0.009362     -0.044640   
Spotify Popularity          0.040435    0.039367 -0.014604     -0.037590   
YouTube Views               0.021260    0.012166  0.009265     -0.034080   
YouTube Likes              -0.005301   -0.001296 -0.000447     -0.012277   
TikTok Posts               -0.018835   -0.022224  0.007762      0.027568   
TikTok Likes                0.030306    0.017554 -0.027445      0.006882   
TikTok Views                0.011635    0.016263 -0.016726      0.023027   
YouTube Playlist Reach      0.003732    0.009759  0.005599      0.018157   
Apple Music Playlist Count  0.024349    0.000472 -0.015590     -0.088376   
AirPlay Spins               0.003587    0.000473  0.000999     -0.002972   
SiriusXM Spins             -0.018413    0.012031  0.023607      0.005145   
Deezer Playlist Count       0.003394   -0.026534 -0.020769     -0.090994   
Deezer Playlist Reach       0.029490    0.003124  0.005663     -0.004979   
Amazon Playlist Count       0.017432    0.006311 -0.003769     -0.030236   
Pandora Streams             0.014638    0.013891 -0.000411     -0.008065   
Pandora Track Stations     -0.000727   -0.007476 -0.009148     -0.012310   
Soundcloud Streams          0.006394   -0.022424  0.015019      0.018579   
Shazam Counts              -0.017489   -0.010833  0.016075     -0.000899   
Explicit Track              0.006830    0.031438  0.008247      0.058769   

                                ISRC  All Time Rank  Track Score  \
Track                       0.030765       0.015619     0.001260   
Album Name                  0.034365      -0.008368     0.007803   
Artist                      0.072608       0.006935    -0.003606   
Release Date                0.015403      -0.024903     0.031244   
ISRC                        1.000000       0.020519     0.067891   
All Time Rank               0.020519       1.000000     0.068856   
Track Score                 0.067891       0.068856     1.000000   
Spotify Streams             0.030205      -0.022230    -0.045950   
Spotify Playlist Count      0.037096      -0.026343    -0.057062   
Spotify Playlist Reach     -0.008297       0.019585     0.041971   
Spotify Popularity          0.123239      -0.005013     0.200948   
YouTube Views               0.004506      -0.024079    -0.034211   
YouTube Likes              -0.008334      -0.028840    -0.036508   
TikTok Posts                0.008779       0.001714    -0.013131   
TikTok Likes                0.009334       0.004951     0.018021   
TikTok Views               -0.002548      -0.014231    -0.011150   
YouTube Playlist Reach     -0.005306      -0.006001    -0.021278   
Apple Music Playlist Count  0.109050       0.032612     0.414375   
AirPlay Spins              -0.013748      -0.005554     0.038238   
SiriusXM Spins             -0.011502      -0.049813     0.010712   
Deezer Playlist Count       0.005739       0.036795     0.349053   
Deezer Playlist Reach      -0.003699      -0.003889    -0.056927   
Amazon Playlist Count       0.096223       0.038609     0.560201   
Pandora Streams             0.008608      -0.003305    -0.001883   
Pandora Track Stations     -0.005432       0.006089     0.031248   
Soundcloud Streams          0.004271       0.019137    -0.

In [ ]:
 df.drop(['Spotify Playlist Reach', 'Apple Music Playlist Count', 'SiriusXM Spins','Deezer Playlist Count',	'Amazon Playlist Count', 'YouTube Playlist Reach', 'Soundcloud Streams','Shazam Counts', 'YouTube Likes'], axis = 1, inplace = True)

In [ ]:
df.corr()

Track  Album Name    Artist  Release Date  \
Track                   1.000000    0.654693 -0.002935      0.010466   
Album Name              0.654693    1.000000  0.003145      0.004980   
Artist                 -0.002935    0.003145  1.000000      0.016887   
Release Date            0.010466    0.004980  0.016887      1.000000   
ISRC                    0.030765    0.034365  0.072608      0.015403   
All Time Rank           0.015619   -0.008368  0.006935     -0.024903   
Track Score             0.001260    0.007803 -0.003606      0.031244   
Spotify Streams        -0.021888    0.003693 -0.022770     -0.012715   
Spotify Playlist Count -0.032318   -0.009352 -0.022571      0.019449   
Spotify Popularity      0.040435    0.039367 -0.014604     -0.037590   
YouTube Views           0.021260    0.012166  0.009265     -0.034080   
TikTok Posts           -0.018835   -0.022224  0.007762      0.027568   
TikTok Likes            0.030306    0.017554 -0.027445      0.006882   
TikTok Views            0.011635    0.016263 -0.016726      0.023027   
AirPlay Spins           0.003587    0.000473  0.000999     -0.002972   
Deezer Playlist Reach   0.029490    0.003124  0.005663     -0.004979   
Pandora Streams         0.014638    0.013891 -0.000411     -0.008065   
Pandora Track Stations -0.000727   -0.007476 -0.009148     -0.012310   
Explicit Track          0.006830    0.031438  0.008247      0.058769   

                            ISRC  All Time Rank  Track Score  Spotify Streams  \
Track                   0.030765       0.015619     0.001260        -0.021888   
Album Name              0.034365      -0.008368     0.007803         0.003693   
Artist                  0.072608       0.006935    -0.003606        -0.022770   
Release Date            0.015403      -0.024903     0.031244        -0.012715   
ISRC                    1.000000       0.020519     0.067891         0.030205   
All Time Rank           0.020519       1.000000     0.068856        -0.022230   
Track Score             0.067891       0.068856     1.000000        -0.045950   
Spotify Streams         0.030205      -0.022230    -0.045950         1.000000   
Spotify Playlist Count  0.037096      -0.026343    -0.057062         0.120215   
Spotify Popularity      0.123239      -0.005013     0.200948        -0.027738   
YouTube Views           0.004506      -0.024079    -0.034211         0.037622   
TikTok Posts            0.008779       0.001714    -0.013131        -0.005505   
TikTok Likes            0.009334       0.004951     0.018021         0.009487   
TikTok Views           -0.002548      -0.014231    -0.011150         0.011900   
AirPlay Spins          -0.013748      -0.005554     0.038238        -0.001196   
Deezer Playlist Reach  -0.003699      -0.003889    -0.056927        -0.010443   
Pandora Streams         0.008608      -0.003305    -0.001883        -0.012701   
Pandora Track Stations -0.005432       0.006089     0.031248         0.003551   
Explicit Track          0.213368       0.008045     0.041801         0.007450   

                        Spotify Playlist Count  Spotify Popularity  \
Track                                -0.032318            0.040435   
Album Name                           -0.009352            0.039367   
Artist                               -0.022571           -0.014604   
Release Date                          0.019449           -0.037590   
ISRC                                  0.037096            0.123239   
All Time Rank                        -0.026343           -0.005013   
Track Score                          -0.057062            0.200948   
Spotify Streams                       0.120215           -0.027738   
Spotify Playlist Count                1.000000           -0.044878   
Spotify Popularity                   -0.044878            1.000000   
YouTube Views                         0.050515            0.001386   
TikTok Posts                         -0.021109            0.040403   
TikTok Likes                         -0.022118         

In [ ]:
X =df.iloc[:,:-1].values
X

array([[2191., 2174., 1754., ...,  931.,  862., 1136.],
       [2559., 2389.,  953., ...,  442., 2999., 1321.],
       [4229., 1580.,  136., ..., 2067., 2447., 2113.],
       ...,
       [1444., 2260., 1055., ..., 3130., 3252., 1332.],
       [2461., 2398.,  131., ..., 3130., 2760., 1332.],
       [2278., 2116.,  125., ...,  656., 2941.,  383.]])

In [ ]:
Y = df.iloc[:,-1].values
Y

array([0, 1, 0, ..., 1, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 0)

***LOGISTIC***

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, Y_train)

LogisticRegression()

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 0]]


In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[548  64]
 [263  45]]


0.6445652173913043

***SUPPORT VECTOR MACHINE***

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, Y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 0]]


In [ ]:
#confusion matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[612   0]
 [308   0]]


0.6652173913043479

***K - nearest neighbor***

In [ ]:
# model training

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 11, metric = 'minkowski')
classifier.fit(X_train, Y_train)

KNeighborsClassifier(n_neighbors=11)

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 0]]


In [ ]:
#confusion matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[497 115]
 [231  77]]


0.6239130434782608

***NAIVE BAYES***

In [ ]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, Y_train)

BernoulliNB()

In [ ]:
#confusion matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[497 115]
 [231  77]]


0.6239130434782608

***DECSION TREE***

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [0 0]]


In [ ]:
#confusion matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[435 177]
 [141 167]]


0.6543478260869565

***Random forest***

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
# confusion matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[435 177]
 [141 167]]


0.6543478260869565

In [ ]:
data = np.array([0.64456,0.62391,0.66521,0.65434,0.65434,0.65434 ])

# providing an index
ser = pd.Series(data, index=['Logistic Regression', 'KNN', 'SVM', 'NAIVE_BAYES', 'DECSION_TREE', 'RANDOM_FOREST'])

print(ser)

Logistic Regression    0.64456
KNN                    0.62391
SVM                    0.66521
NAIVE_BAYES            0.65434
DECSION_TREE           0.65434
RANDOM_FOREST          0.65434
dtype: float64
